### ISSUE TITLE
Discuss the exact name of the system

### ISSUE THREAD

**Issue by zxcv1050135042** [Team-Arbitrary/Team-Arbitrary.github.io#7]
- Professional Development Tracking Tool (Automatic tracking features?)
- Professional Development Management System
- Professional Development Manager
- Professional Development Event Planner (Planning features?)
- Professional Development Activity Stats
- Professional Development Notebook
- others...

Feel free to suggest your favorite name   ; )

**Comment by josghost** [comment]
I like the Professional Development Management System and the Professional Development Notebook as the names

**Comment by zxcv1050135042** [comment]
Result: Professional Development Notebook
