### ISSUE TITLE
User Status Radio Buttons

### ISSUE THREAD

**Issue by josghost** [Team-Arbitrary/Team-Arbitrary.github.io#9]
I am wondering if we are keeping the user status radio buttons in the Professional Development Completion Form, or if we are going to move this status option to the account page. These are the radio buttons I'm referring to: 
![image](https://user-images.githubusercontent.com/59345761/164138854-57eb3be6-fd90-4cda-8334-92dba6e7b097.png)

Do we want to remove these buttons completely from the form? Thanks in advance for letting me know.

**Comment by zxcv1050135042** [comment]
UserProfile Page has been completed :) 

welcome to check https://teamarbitraryproject.000webhostapp.com/
